version: "3.8"

services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
##  image: flask-demo:latest
    environment:
      - REDIS_HOST=redis-server

  redis-server:
    image: redis:latest

  client:
    image: xiaopeng163/net-box:latest
    command: sh -c "while true; do sleep 3600; done;"
